#!/usr/bin/env python

"""
Prints out the current time and the number of google hits for a particular 
domain.  Suitable for running from cron, like this example to count every hour

0 * * * * /home/ed/Projects/google-count/google-count id.loc.gov >> /home/ed/Projects/google-count/id.loc.gov
"""

import re
import sys
import urllib2
import datetime

if len(sys.argv) != 2:
    print "usage: count.py domain"
    sys.exit(1)

domain = sys.argv[1]
url = "http://www.google.com/search?q=site:%s" % domain
request = urllib2.Request(url, headers={'User-Agent': "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30)"})
html = urllib2.urlopen(request).read()

now = datetime.datetime.now()
count = re.search(r'About ([\d,]+) results', html).group(1).replace(',', '')
print "%s\t%s" % (now, count)
